site_name: Introduction to Robotics

theme:
    name: material
    logo: assets/area_53.png
    favicon: assets/area_53.png
    features:
        - navigation.footer
        - header.autohide

    palette:
        primary: green
        accent: green
        scheme: slate

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
    - 'Recommended Reading Order': './recommended-reading-order.md'
    - 'Introduction': './introduction.md'
    - 'Hardware':
          - 'Introduction': './hardware/introduction.md'
          - 'The Basics':
                - 'Tools': './the-basics/tools.md'
                - 'Parts': './the-basics/parts.md'
          - 'Theory':
                - 'Torque': './hardware/theory/torque-speed.md'
                - 'Gear Ratios': './hardware/theory/gear-ratios.md'
                - 'Stress': './hardware/theory/stress.md'
          - 'Techniques':
                - 'Joints': './hardware/techniques/joints.md'
                - 'Bracing': './hardware/techniques/bracing.md'
                - 'Boxing': './hardware/techniques/boxing.md'
                - 'Canteleveration': './hardware/techniques/canteleveration.md'
          - 'Subsystems':
                - 'Introduction': './hardware/subsystems/introduction.md'
                - 'Drivetrains': './hardware/subsystems/drivetrain.md'
                - 'Lifts': './hardware/subsystems/lifts.md'
                - 'Intakes': './hardware/subsystems/intakes.md'
                - 'Shooting': './hardware/subsystems/shooting.md'
                - 'Climing': './hardware/subsystems/climbing.md'
          - 'CAD':
                - 'Introduction': './hardware/cad/introduction.md'
                - 'Onshape': './hardware/cad/onshape.md'
                - 'Fusion 360': './hardware/cad/fusion360.md'
                - 'Inventor': './hardware/cad/inventor.md'
                - 'Solidworks': './hardware/cad/solidworks.md'
    - 'Software':
          - 'Introduction': './software/introduction.md'
          - 'Basics':
                - 'Variables': './software/basics/variables.md'
                - 'Operators': './software/basics/operators.md'
                - 'Control Flow': './software/basics/control-flow.md'
                - 'Functions': './software/basics/functions.md'
                - 'Scope': './software/basics/scope.md'
                - 'Enumerations': './software/basics/enums.md'
                - 'Namespaces': './software/basics/namespaces.md'
                - 'Headers': './software/basics/headers.md'
                - 'Object Oriented Programming': './software/basics/oop.md'
          - 'Conventions':
                - 'Introduction': './software/conventions/introduction.md'
                - 'Descriptive Variables': './software/conventions/descriptive-variables.md'
                - 'Naming Conventions': './software/conventions/naming-conventions.md'
                - 'Program Organization': './software/conventions/program-organization.md'
                - 'Comments': './software/conventions/comments.md'
          - 'Programming the Robot':
                - 'Introduction': './software/programming-the-bot/introduction.md'
                - 'Tank Drive': './software/programming-the-bot/tank-drive.md'
                - 'Arcade Drive': './software/programming-the-bot/arcade-drive.md'
                - 'Toggling Subsystems': './software/programming-the-bot/subsystem-toggling.md'
          - 'Git':
                - 'Introduction': './software/git/introduction.md'
                - 'Getting Started': './software/git/getting-started.md'
                - 'Commits and Staging': './software/git/commits-and-staging.md'
                - 'Branches': './software/git/branches.md'
                - 'Pushing and Pulling': './software/git/pushing-and-pulling.md'
                - 'Remote Branches': './software/git/remote-branches.md'
          - 'Advanced Concepts':
                - 'Introduction': './software/advanced-concepts/introduction.md'
                - 'Control Loops': './software/advanced-concepts/control-loops.md'
                - 'Bang Bang Controller': './software/advanced-concepts/bang-bang.md'
                - 'PID Controller': './software/advanced-concepts/pid.md'
                - 'Odometry': './software/advanced-concepts/odometry.md'
                - 'Moving to 2D Points': './software/advanced-concepts/move-to-point.md'
                - 'Boomerang Controller': './software/advanced-concepts/boomerang.md'
    - 'Driving': './driving.md'
    - 'Notebooking': './notebooking.md'
    - 'Leading': './leading.md'
    - 'The Season': './the-season.md'
    - 'The Tournament': './the-tournament.md'
    - 'Theory': './theory.md'
    - 'Resources': './resources.md'
    - 'About the Authors': './about-the-authors.md'
