site_name: Introduction to Robotics

theme:
    name: material
    logo: assets/area_53.png
    favicon: assets/area_53.png
    features:
        - navigation.footer
        - header.autohide

    palette:
        primary: green
        accent: lime
        scheme: slate

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
    - 'Recommended Reading Order': './recommended-reading-order.md'
    - 'Introduction': './introduction.md'
    - 'The Basics':
          - 'Tools': './the-basics/tools.md'
          - 'Parts': './the-basics/parts.md'
    - 'Subsystems':
          - 'Drivetrains': './subsystems/drivetrains.md'
          - 'Lifts': './subsystems/lifts.md'
          - 'Intakes': './subsystems/intakes.md'
          - 'Shooting': './subsystems/shooting.md'
    - 'Building Techniques':
          - 'Introduction': './building-techniques/introduction.md'
          - 'Stationary': './building-techniques/stationary.md'
          - 'Moving': './building-techniques/moving.md'
          - 'Drivetrain': './building-techniques/drivetrain.md'
    - 'Coding Techniques':
          - 'Introduction': './coding-techniques/introduction.md'
          - 'Basics':
                - 'Variables': './coding-techniques/basics/variables.md'
                - 'Operators': './coding-techniques/basics/operators.md'
                - 'Control Flow': './coding-techniques/basics/control-flow.md'
                - 'Functions': './coding-techniques/basics/functions.md'
                - 'Scope': './coding-techniques/basics/scope.md'
                - 'Namespaces': './coding-techniques/basics/namespaces.md'
                - 'Headers': './coding-techniques/basics/headers.md'
                - 'Object Oriented Programming': './coding-techniques/basics/oop.md'
          - 'Conventions':
                - 'Introduction': './coding-techniques/conventions/introduction.md'
                - 'Descriptive Variables': './coding-techniques/conventions/descriptive-variables.md'
                - 'Naming Conventions': './coding-techniques/conventions/naming-conventions.md'
                - 'Program Organization': './coding-techniques/conventions/program-organization.md'
                - 'Comments': './coding-techniques/conventions/comments.md'
          - 'Programming the Robot':
                - 'Introduction': './coding-techniques/programming-the-bot/introduction.md'
                - 'Tank Drive': './coding-techniques/programming-the-bot/tank-drive.md'
                - 'Arcade Drive': './coding-techniques/programming-the-bot/arcade-drive.md'
                - 'Toggling Subsystems': './coding-techniques/programming-the-bot/subsystem-toggling.md'
          - 'Git':
                - 'Introduction': './coding-techniques/git/introduction.md'
                - 'Getting Started': './coding-techniques/git/getting-started.md'
                - 'Commits and Staging': './coding-techniques/git/commits-and-staging.md'
                - 'Branches': './coding-techniques/git/branches.md'
                - 'Pushing and Pulling': './coding-techniques/git/pushing-and-pulling.md'
                - 'Remote Branches': './coding-techniques/git/remote-branches.md'
          - 'Advanced Concepts':
                - 'Introduction': './coding-techniques/advanced-concepts/introduction.md'
                - 'Bang Bang Controller': './coding-techniques/advanced-concepts/bang-bang.md'
                - 'PID Controller': './coding-techniques/advanced-concepts/pid.md'
                - 'Odometry': './coding-techniques/advanced-concepts/odometry.md'
                - 'Moving to 2D Points': './coding-techniques/advanced-concepts/move-to-point.md'
                - 'Boomerang Controller': './coding-techniques/advanced-concepts/boomerang.md'
    - 'Driving Techniques': './driving-techniques.md'
    - 'Notebooking Techniques': './notebooking-techniques.md'
    - 'Leading Techniques': './leading-techniques.md'
    - 'The Season': './the-season.md'
    - 'The Tournament': './the-tournament.md'
    - 'Theory': './theory.md'
    - 'Resources': './resources.md'
    - 'About the Authors': './about-the-authors.md'
