site_name: Introduction to Robotics

theme:
    name: material
    logo: assets/area_53.png
    favicon: assets/area_53.png
    features:
        - navigation.tabs
        - navigation.footer
        - header.autohide
        - content.code.copy
        - content.tabs.link

    palette:
        primary: green
        accent: light green
        scheme: slate

plugins:
    - search:
          lang: en
          separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - minify:
          minify_html: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Area-53-Robotics
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/@team53robotics
        - icon: fontawesome/brands/instagram
          link: https://www.instagram.com/area53robotics/

copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - 'Home': 'index.md'
    - 'Introduction':
          - 'Foreword': './introduction/foreword.md'
          - 'Design Philosophy': './introduction/philosophy.md'
          - 'Recommended Reading Order': './introduction/recommended-reading-order.md'
    - 'Hardware':
          - 'Introduction': './hardware/introduction.md'
          - 'Tools': './hardware/tools.md'
          - 'Parts': './hardware/parts.md'
          - 'Theory': './hardware/theory.md'
          - 'Techniques': './hardware/techniques.md'
          - 'Subsystems': './hardware/subsystems.md'
          - 'CAD':
                - 'Introduction': './hardware/cad/introduction.md'
                - 'Onshape': './hardware/cad/onshape.md'
                - 'Fusion 360': './hardware/cad/fusion360.md'
                - 'Inventor': './hardware/cad/inventor.md'
                - 'Solidworks': './hardware/cad/solidworks.md'
    - 'Software':
          - 'Introduction': './software/introduction.md'
          - 'Basics': './software/basics.md'
          - 'Conventions': './software/conventions.md'
          - 'Examples': './software/examples.md'
          - 'Git': './software/git.md'
          - 'Advanced Concepts':
                - 'Introduction': './software/advanced-concepts/introduction.md'
                - 'Control Loops': './software/advanced-concepts/control-loops.md'
                - 'Bang Bang Controller': './software/advanced-concepts/bang-bang.md'
                - 'PID Controller': './software/advanced-concepts/pid.md'
                - 'Odometry': './software/advanced-concepts/odometry.md'
                - 'Moving to 2D Points': './software/advanced-concepts/move-to-point.md'
                - 'Boomerang Controller': './software/advanced-concepts/boomerang.md'
    - 'Driving': './driving.md'
    - 'Notebooking': './notebooking.md'
    - 'Leading': './leading.md'
    - 'The Game':
          - 'The Season': './the-season.md'
          - 'The Tournament': './the-tournament.md'
    - 'Theory': './theory.md'
    - 'Appendix':
          - 'Resources': './appendix/resources.md'
          - 'About the Authors': './appendix/about-the-authors.md'
