site_name: Introduction to Robotics

theme:
    name: material
    logo: assets/area_53.png
    favicon: assets/area_53.png
    features:
        - navigation.tabs
        - navigation.footer
        - header.autohide
        - content.code.copy
        - content.tabs.link

    palette:
        primary: green
        accent: light green
        scheme: slate

plugins:
    - search:
          lang: en
          separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - minify:
          minify_html: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Area-53-Robotics
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/@team53robotics
        - icon: fontawesome/brands/instagram
          link: https://www.instagram.com/area53robotics/

copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
    - 'Introduction':
          - 'Foreword': './introduction/foreword.md'
          - 'Recommended Reading Order': './introduction/recommended-reading-order.md'
    - 'Hardware':
          - 'Introduction': './hardware/introduction.md'
          - 'Basics':
                - 'Tools': './hardware/basics/tools.md'
                - 'Parts': './hardware/basics/parts.md'
          - 'Theory':
                - 'Torque': './hardware/theory/torque-speed.md'
                - 'Gear Ratios': './hardware/theory/gear-ratios.md'
                - 'Stress': './hardware/theory/stress.md'
          - 'Techniques':
                - 'Joints': './hardware/techniques/joints.md'
                - 'Bracing': './hardware/techniques/bracing.md'
                - 'Boxing': './hardware/techniques/boxing.md'
                - 'Canteleveration': './hardware/techniques/canteleveration.md'
          - 'Subsystems':
                - 'Drivetrains': './hardware/subsystems/drivetrain.md'
                - 'Lifts': './hardware/subsystems/lifts.md'
                - 'Intakes': './hardware/subsystems/intakes.md'
                - 'Shooting': './hardware/subsystems/shooting.md'
                - 'Climing': './hardware/subsystems/climbing.md'
          - 'CAD':
                - 'Introduction': './hardware/cad/introduction.md'
                - 'Onshape': './hardware/cad/onshape.md'
                - 'Fusion 360': './hardware/cad/fusion360.md'
                - 'Inventor': './hardware/cad/inventor.md'
                - 'Solidworks': './hardware/cad/solidworks.md'
    - 'Software':
          - 'Introduction': './software/introduction.md'
          - 'Basics':
                - 'Variables': './software/basics/variables.md'
                - 'Operators': './software/basics/operators.md'
                - 'Control Flow': './software/basics/control-flow.md'
                - 'Functions': './software/basics/functions.md'
                - 'Scope': './software/basics/scope.md'
                - 'Enumerations': './software/basics/enums.md'
                - 'Namespaces': './software/basics/namespaces.md'
                - 'Headers': './software/basics/headers.md'
                - 'Object Oriented Programming': './software/basics/oop.md'
          - 'Conventions':
                - 'Introduction': './software/conventions/introduction.md'
                - 'Descriptive Variables': './software/conventions/descriptive-variables.md'
                - 'Naming Conventions': './software/conventions/naming-conventions.md'
                - 'Program Organization': './software/conventions/program-organization.md'
                - 'Comments': './software/conventions/comments.md'
          - 'Programming the Robot':
                - 'Introduction': './software/programming-the-bot/introduction.md'
                - 'Tank Drive': './software/programming-the-bot/tank-drive.md'
                - 'Arcade Drive': './software/programming-the-bot/arcade-drive.md'
                - 'Toggling Subsystems': './software/programming-the-bot/subsystem-toggling.md'
          - 'Git':
                - 'Introduction': './software/git/introduction.md'
                - 'Local Repositories': './software/git/local-repo.md'
                - 'Commits': './software/git/commits.md'
                - 'Branches': './software/git/branches.md'
                - 'Merging': './software/git/merging.md'
                - 'Remote Repositories': './software/git/remote-repo.md'
                - 'Further Reading': './software/git/further-reading.md'
          - 'Advanced Concepts':
                - 'Introduction': './software/advanced-concepts/introduction.md'
                - 'Control Loops': './software/advanced-concepts/control-loops.md'
                - 'Bang Bang Controller': './software/advanced-concepts/bang-bang.md'
                - 'PID Controller': './software/advanced-concepts/pid.md'
                - 'Odometry': './software/advanced-concepts/odometry.md'
                - 'Moving to 2D Points': './software/advanced-concepts/move-to-point.md'
                - 'Boomerang Controller': './software/advanced-concepts/boomerang.md'
    - 'Driving': './driving.md'
    - 'Notebooking': './notebooking.md'
    - 'Leading': './leading.md'
    - 'The Game':
          - 'The Season': './the-season.md'
          - 'The Tournament': './the-tournament.md'
    - 'Theory': './theory.md'
    - 'Appendix':
          - 'Resources': './appendix/resources.md'
          - 'About the Authors': './appendix/about-the-authors.md'
